name: Build and Deploy Android App

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    name: Build and Publish to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'


      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release-key.jks

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.juliuscanute.tkural
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production 
          inAppUpdatePriority: 3 